# Generated by Django 5.1.5 on 2025-01-30 00:39

import perfil.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('nameTag', models.CharField(max_length=20)),
                ('estrelas', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=perfil.models.enviar_imagem_perfil)),
            ],
        ),
    ]
