# Generated by Django 5.1.5 on 2025-02-03 23:30

import django.db.models.deletion
import perfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_Crompra', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('valorPago', models.FloatField(default=0)),
                ('dataPedido', models.DateField(auto_now_add=True)),
                ('dataEntrega', models.DateField(blank=True, null=True)),
                ('particao', models.IntegerField(default=100)),
                ('estatus', models.CharField(max_length=20)),
                ('alerta', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItensMercado',
            fields=[
                ('id_ItemMercado', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.FloatField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=perfil.models.enviar_imagem_itenMercado)),
                ('tiposCor', models.JSONField(blank=True, default=dict)),
                ('tiposFundo', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('nameTag', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('estrelas', models.FloatField(default=0)),
                ('particao', models.IntegerField(default=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=perfil.models.enviar_imagem_perfil)),
                ('outrosSites', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Itemcompra',
            fields=[
                ('id_ItemCompra', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('detalhes', models.CharField(max_length=100)),
                ('tipoCor', models.IntegerField(default=0)),
                ('tipoFundo', models.IntegerField(default=0)),
                ('id_Crompra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.compra')),
                ('itensMercado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.itensmercado')),
            ],
        ),
        migrations.AddField(
            model_name='itensmercado',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.perfil'),
        ),
        migrations.CreateModel(
            name='ItensCarrinho',
            fields=[
                ('id_ItemCarrinho', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('detalhes', models.CharField(max_length=100)),
                ('tipoCor', models.IntegerField(default=0)),
                ('tipoFundo', models.IntegerField(default=0)),
                ('itensMercado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.itensmercado')),
                ('perfilComprador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='perfilComprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.perfil'),
        ),
    ]
