# Generated by Django 5.1.5 on 2025-02-01 16:10

import django.db.models.deletion
import perfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.FloatField(default=-1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=perfil.models.enviar_imagem_perfil)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.perfil')),
            ],
        ),
    ]
