# Generated by Django 5.1.5 on 2025-02-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='tipoCor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='tipoFundo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='itenscarrinho',
            name='tipoCor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='itenscarrinho',
            name='tipoFundo',
            field=models.CharField(max_length=20),
        ),
    ]
