# Generated by Django 5.1.5 on 2025-02-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_itemcompra_tipocor_alter_itemcompra_tipofundo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
    ]
